/**
 * /terms — OperaAI, Inc. Terms of Service (main agreement).
 * Derived from the counsel-drafted beta agreement, generalized for GA and
 * expanded to cover the current platform surface (post-consult treatment
 * videos, pre-consult welcome experiences, the Ask Opera patient assistant,
 * patient share links, engagement analytics, PMS integrations, billing).
 * NOTE: have counsel re-review before enterprise signature use.
 */

export const metadata = { title: "OperaAI — Terms of Service" };

const EFFECTIVE_DATE = "July 22, 2026";

function Section({
  n,
  title,
  children,
}: {
  n: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section id={`s${n}`}>
      <h2 className="cf-display mb-2 mt-10 text-[20px] font-medium text-[#1a1a17]">
        {n}. {title}
      </h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="cf-body text-[14.5px] leading-relaxed text-[#3d423e]">{children}</p>;
}

function Caps({ children }: { children: React.ReactNode }) {
  return (
    <p className="cf-body text-[13.5px] font-medium uppercase leading-relaxed tracking-[0.01em] text-[#3d423e]">
      {children}
    </p>
  );
}

function Def({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <p className="cf-body text-[14.5px] leading-relaxed text-[#3d423e]">
      <span className="font-semibold text-[#1a1a17]">&ldquo;{term}&rdquo;</span> {children}
    </p>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="mx-auto max-w-3xl px-6 pb-24 pt-14 sm:px-8">
        <p className="cf-mono text-[11px] uppercase tracking-[0.22em] text-[#5f7a61]">
          OperaAI, Inc.
        </p>
        <h1 className="cf-display mt-2 text-[clamp(1.9rem,4vw,2.6rem)] font-light tracking-[-0.02em] text-[#1a1a17]">
          Terms of Service
        </h1>
        <p className="cf-body mt-2 text-[14px] text-[#5e6a60]">
          Effective {EFFECTIVE_DATE} · OperaAI, Inc., a Delaware corporation with offices at 13342
          Emeric Ct, Centreville, VA 20120 (&ldquo;OperaAI&rdquo;, &ldquo;Opera&rdquo;,
          &ldquo;we&rdquo;, &ldquo;us&rdquo;)
        </p>

        <div className="mt-8 rounded-2xl border border-[#5f7a61]/25 bg-[#5f7a61]/[0.05] px-6 py-5">
          <p className="cf-body text-[14px] leading-relaxed text-[#3e5540]">
            These Terms of Service (these &ldquo;Terms&rdquo;), together with any order form,
            subscription selection, or online signup flow referencing them (each an &ldquo;Order
            Form&rdquo;), form a binding agreement (this &ldquo;Agreement&rdquo;) between OperaAI and
            the practice, organization, or entity that registers for or uses the Platform
            (&ldquo;Customer&rdquo;). By creating an account, executing an Order Form, clicking to
            accept, or using the Platform, Customer agrees to this Agreement. OperaAI and Customer
            are each a &ldquo;Party&rdquo; and together the &ldquo;Parties.&rdquo;
          </p>
        </div>

        <Section n="1" title="Definitions">
          <Def term="Account">
            means the account(s) associated with the Platform that enable Users to access and use the
            Platform. Customer receives at least one administrator Account to manage its subscription,
            its Users, and its use of the Platform. Accounts may be provisioned by self-serve signup,
            by OperaAI on Customer&rsquo;s behalf, or through an integration partner.
          </Def>
          <Def term="Confidential Information">
            means the terms and conditions of this Agreement, all information in Accounts, Customer
            Materials, and any information that is identified as confidential at the time of
            disclosure or that should reasonably be understood to be confidential given its nature and
            the circumstances of disclosure.
          </Def>
          <Def term="Customer Materials">
            means any content, Inputs, Outputs, materials, data, images, video footage (including
            office-tour footage), names and likenesses (solely to the extent agreed by the Parties),
            trademarks, logos, welcome notes, and information uploaded or entered on, or generated by,
            the Platform by or on behalf of Customer or its Users, including patient information
            submitted to personalize Outputs.
          </Def>
          <Def term="Input">
            means the Customer Materials and other information input into the Platform or otherwise
            provided to OperaAI, including patient names, appointment details, diagnoses, treatment
            plans, consultation notes and transcripts, provider names, clinic branding, and questions
            submitted by patients through the Platform.
          </Def>
          <Def term="Intellectual Property Rights">
            means all copyrights, neighboring rights, database rights, patent rights, trademark
            rights, trade name rights, design rights, trade secret rights, rights in domain names,
            rights of publicity, rights of privacy, rights in Confidential Information (including
            know-how and trade secrets) and any other intellectual property rights, whether registered
            or unregistered, including all applications, renewals, extensions, and similar or
            equivalent rights anywhere in the world.
          </Def>
          <Def term="Output">
            means output generated by or through the Platform, which may include personalized
            patient-education videos (including post-consultation treatment videos and pre-consultation
            welcome videos), patient-facing web pages and share links, responses generated by the Ask
            Opera assistant, captions, voiceover audio, engagement summaries and analytics, and
            post-consultation surveys.
          </Def>
          <Def term="Patient Pages">
            means the patient-facing web pages hosted by OperaAI and reachable through unique share
            links, on which patients may view Outputs and submit questions to the Ask Opera assistant.
          </Def>
          <Def term="Platform">
            means OperaAI&rsquo;s online software-as-a-service solution, including its clinic portal,
            video generation pipeline, pre-consultation welcome experiences, Ask Opera assistant,
            Patient Pages, analytics, administrative tooling, APIs, and any integrations with
            practice-management systems identified in an Order Form or made available to Customer.
          </Def>
          <Def term="Services">
            means the provision of the Platform and any other services OperaAI provides to Customer
            under this Agreement or an applicable Order Form.
          </Def>
          <Def term="Subscription Fees">
            means the fees payable by Customer for use of the Platform, as set out in the applicable
            Order Form, the pricing selected at signup, or as otherwise agreed in writing.
          </Def>
          <Def term="Support">
            means the support made available to Customer through online user guides, knowledge bases,
            and self-help tools regarding the use of the Platform, and a helpdesk available via phone,
            text, email (opera@getopera.ai), or other means made available by OperaAI.
          </Def>
          <Def term="User">
            means an employee of Customer or other person authorized through Customer&rsquo;s
            administrator Account to access and use the Platform on behalf of Customer.
          </Def>
        </Section>

        <Section n="2" title="Applicability">
          <P>
            2.1 These Terms apply to this Agreement and to all access to and use of the Platform by
            Customer and its Users, however provisioned.
          </P>
          <P>2.2 Any general (purchase order) conditions of Customer are hereby expressly rejected.</P>
          <P>
            2.3 In the event of inconsistencies between these Terms and an Order Form confirmed by
            both Parties in writing, the provisions of the confirmed Order Form prevail.
          </P>
        </Section>

        <Section n="3" title="The Platform">
          <P>
            3.1 <span className="font-medium text-[#1a1a17]">What Opera does.</span> The Platform uses
            artificial-intelligence technologies to generate personalized patient communication and
            education content on behalf of dental, orthodontic, and other specialty healthcare
            practices. Depending on Customer&rsquo;s subscription, this may include: (a)
            post-consultation treatment videos that explain a patient&rsquo;s condition, diagnosis (if
            any), recommended treatment, and next steps in plain language; (b) pre-consultation
            welcome experiences, including personalized welcome videos and Patient Pages that may
            incorporate Customer&rsquo;s own office footage, branding, and welcome notes; (c) the Ask
            Opera assistant, which answers patient questions on Patient Pages using context supplied
            by Customer; (d) engagement records and analytics that surface patient questions and
            activity back to Customer; and (e) integrations with practice-management systems.
          </P>
          <P>
            3.2 <span className="font-medium text-[#1a1a17]">Content review.</span> Certain Customer
            Materials intended for patient-facing display (for example office-tour footage and welcome
            notes) may be subject to review by OperaAI before going live. OperaAI may decline or
            require changes to submitted materials at its reasonable discretion.
          </P>
          <P>
            3.3 <span className="font-medium text-[#1a1a17]">Share links.</span> Patient Pages are
            reachable by unguessable, unique links rather than patient logins. Customer is responsible
            for delivering share links only to the intended patient (or their guardian) and for its
            choice of delivery channel (including SMS or email), including any consents required for
            that channel.
          </P>
        </Section>

        <Section n="4" title="Right of use and limitations">
          <P>
            4.1 <span className="font-medium text-[#1a1a17]">Use of Platform.</span> Subject to
            Customer&rsquo;s compliance with this Agreement and payment of applicable Subscription
            Fees, OperaAI grants Customer a non-transferable, non-exclusive right, during the
            Subscription Term, to permit Users to access and use the Platform, and to share Outputs
            with Customer&rsquo;s own patients for their personal, non-commercial use, within any usage
            limits specified in the applicable Order Form or plan.
          </P>
          <P>
            4.2 <span className="font-medium text-[#1a1a17]">Services.</span> OperaAI shall use
            commercially reasonable efforts to perform the Services.
          </P>
          <P>
            4.3 <span className="font-medium text-[#1a1a17]">License to Customer Materials.</span> To
            make the Platform available to Customer, Customer grants OperaAI a non-exclusive right to
            use, copy, process, distribute, and display Customer Materials solely in connection with
            operating the Platform and performing the Services on Customer&rsquo;s behalf (including
            generating Outputs, hosting Patient Pages, and rendering Customer&rsquo;s footage,
            branding, and notes into videos). Customer Materials are encrypted in transit and at rest
            and are logically separated from the data of other OperaAI customers. OperaAI uses
            Customer Materials only as necessary to provide the Services, to comply with applicable
            law, and as otherwise permitted by this Agreement. OperaAI takes no responsibility and
            assumes no liability for Inputs provided by or on behalf of Customer; Customer is solely
            responsible for its Inputs, including ensuring they do not violate applicable law.
            Customer represents and warrants that it owns, controls, or has lawfully obtained all
            rights, permissions, and consents necessary to grant the rights set forth herein,
            including any patient consents or authorizations required for OperaAI to process patient
            information and provide the Platform and Outputs.
          </P>
          <P>
            4.4 <span className="font-medium text-[#1a1a17]">Restrictions.</span> Customer may not,
            directly or indirectly: (a) reverse engineer, decompile, modify, disassemble, or otherwise
            attempt to discover or make derivative works of the source code, underlying ideas, user
            interface techniques, or algorithms of the Platform; (b) cause undue strain on the
            Platform through excessive or non-standard use, including automated bulk generation
            outside plan limits; (c) use the Platform for any purpose outside its intended design and
            Customer&rsquo;s authorized use; (d) license, sell, rent, lease, transfer, assign,
            distribute, display, host, outsource, or otherwise commercially exploit the Platform or
            make it available to any third party (other than sharing Outputs with Customer&rsquo;s own
            patients as intended); (e) replicate or use any aspect of the Platform to build or support
            a competing product or service; or (f) use the Platform to create content that is
            misleading, unlawful, or presented to patients as clinical advice without professional
            review. Any information supplied by or obtained from OperaAI may not be disclosed to any
            third party or used to create any software or service substantially similar to the
            Platform.
          </P>
          <P>
            4.5 <span className="font-medium text-[#1a1a17]">Access credentials.</span> Platform login
            details and API keys may not be shared with, used by, or transferred to any third party
            without OperaAI&rsquo;s written consent. Customer is responsible for safeguarding its
            Account credentials and API keys and for all activity occurring under them. Customer shall
            notify OperaAI promptly at opera@getopera.ai of any suspected compromise, and OperaAI will
            rotate affected credentials.
          </P>
        </Section>

        <Section n="5" title="Fees and payment terms">
          <P>
            5.1 <span className="font-medium text-[#1a1a17]">Fees.</span> Customer shall pay the
            Subscription Fees and any other fees set out in the applicable Order Form or selected at
            signup. Unless otherwise stated, Subscription Fees are payable monthly in advance, are
            irrevocable, and are non-refundable except where required by law. OperaAI has no
            obligation to provide access to the Platform until applicable Subscription Fees have been
            paid.
          </P>
          <P>
            5.2 <span className="font-medium text-[#1a1a17]">Online billing and trials.</span> Where
            Customer subscribes online, payment is processed by OperaAI&rsquo;s payment processor
            (currently Stripe). If a free trial is offered, the subscription converts automatically to
            a paid plan at the rate shown at signup unless canceled before the trial ends.
            Subscriptions renew monthly until canceled; cancellation takes effect at the end of the
            current billing period. OperaAI may change pricing with at least thirty (30) days&rsquo;
            notice, effective on Customer&rsquo;s next renewal.
          </P>
          <P>
            5.3 <span className="font-medium text-[#1a1a17]">Taxes.</span> All amounts are stated
            exclusive of any applicable sales, use, GST, withholding, or value-added taxes, which will
            be added where applicable and are payable by Customer.
          </P>
          <P>
            5.4 <span className="font-medium text-[#1a1a17]">Non-payment.</span> OperaAI may suspend
            access to the Platform for accounts with overdue fees after reasonable notice.
          </P>
        </Section>

        <Section n="6" title="Third-party software and integrations">
          <P>
            The Platform may incorporate third-party software and services (including AI model
            providers, telephony/SMS providers, payment processors, and cloud infrastructure) governed
            by separate licenses, which are incorporated by reference into this Agreement, and
            Customer agrees to their terms. Practice-management systems and other integration partners
            (for example, Greyfinch) are separate companies; Customer&rsquo;s use of those systems is
            governed by Customer&rsquo;s agreements with them, and OperaAI is not responsible for
            their acts, omissions, or availability. Customer shall not modify or combine the Platform
            or any third-party software in any manner that would cause the Platform to become subject
            to the terms of any third-party license.
          </P>
        </Section>

        <Section n="7" title="Platform updates; disclaimer">
          <P>
            7.1 <span className="font-medium text-[#1a1a17]">Platform.</span> OperaAI will use
            commercially reasonable efforts, in accordance with applicable industry standards, to
            provide and maintain the Platform in a manner that minimizes errors and interruptions.
            OperaAI makes no further warranty unless otherwise agreed in writing.
          </P>
          <P>
            7.2 <span className="font-medium text-[#1a1a17]">Errors.</span> During the Subscription
            Term, OperaAI will use commercially reasonable efforts to correct faults in the Platform
            within a reasonable period, provided Customer gives OperaAI a detailed written description
            of the fault. OperaAI may deploy temporary solutions, workarounds, or restrictions.
          </P>
          <P>
            7.3 <span className="font-medium text-[#1a1a17]">Updates.</span> OperaAI may make
            available, at no additional cost, updates and upgrades to the Platform, including
            improvements, new versions, new functionality, patches, and fixes. OperaAI may add,
            change, or retire features of the Platform, provided it does not materially reduce the
            core functionality Customer has paid for during a paid term.
          </P>
          <Caps>
            7.4 Disclaimer. TO THE MAXIMUM EXTENT PERMITTED BY LAW, OPERAAI DISCLAIMS ALL WARRANTIES,
            EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND ALL WARRANTIES ARISING OUT OF USAGE IN
            TRADE, COURSE OF DEALING, AND COURSE OF PERFORMANCE. OPERAAI FURTHER DISCLAIMS ANY
            WARRANTY THAT (A) THE PLATFORM WILL MEET CUSTOMER&rsquo;S REQUIREMENTS OR WILL BE
            CONTINUOUSLY AVAILABLE, UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (B) THE RESULTS
            OBTAINED FROM USE OF THE PLATFORM WILL BE EFFECTIVE, ACCURATE, OR RELIABLE; (C) THE
            QUALITY OF THE PLATFORM WILL MEET CUSTOMER&rsquo;S EXPECTATIONS; OR (D) ANY ERRORS OR
            DEFECTS IN THE PLATFORM WILL BE CORRECTED.
          </Caps>
        </Section>

        <Section n="8" title="Support">
          <P>
            OperaAI provides Support by giving Customer and its Users access to online user guides,
            knowledge bases, and self-help resources regarding use of the Platform. The helpdesk is
            available via phone, text, email (opera@getopera.ai), or other means made available by
            OperaAI. A first response will be provided within forty-eight (48) hours of receipt of a
            call, text, or email on business days, Eastern U.S. time.
          </P>
        </Section>

        <Section n="9" title="Intellectual property; artificial intelligence">
          <P>
            9.1 <span className="font-medium text-[#1a1a17]">Platform and Services.</span> OperaAI
            retains all right, title, and interest (including all Intellectual Property Rights) in and
            to the Platform and Services — including application development, business and technical
            methodologies, video templates, compositions, and implementation processes used to develop
            or provide them — and all updates, upgrades, enhancements, customizations, revisions,
            modifications, and future releases. Except for the limited access and use rights granted
            in this Agreement, Customer acquires no interest in the Platform. For clarity, such rights
            do not extend to Customer Materials.
          </P>
          <P>
            9.2 <span className="font-medium text-[#1a1a17]">Feedback.</span> If Customer provides
            suggestions, comments, ideas, survey responses, defect reports, or other feedback about
            the Platform (&ldquo;Feedback&rdquo;), OperaAI shall own all right, title, and interest in
            and to such Feedback, and Customer hereby makes and agrees to make all assignments
            necessary to achieve such ownership.
          </P>
          <P>
            9.3 <span className="font-medium text-[#1a1a17]">Customer Materials.</span> Except for the
            limited rights granted in this Agreement, Customer retains all right, title, and interest
            (including all Intellectual Property Rights) in and to Customer Materials.
          </P>
          <Caps>
            9.4 Artificial intelligence. THE PLATFORM INCLUDES FEATURES SUPPORTED BY
            ARTIFICIAL-INTELLIGENCE TECHNOLOGIES, INCLUDING GENERATED VIDEO NARRATION AND THE ASK
            OPERA ASSISTANT. DUE TO THE NATURE OF MACHINE LEARNING, OUTPUT MAY NOT BE UNIQUE ACROSS
            USERS AND THE PLATFORM MAY GENERATE THE SAME OR SIMILAR OUTPUT FOR OTHER USERS. USE OF THE
            PLATFORM MAY RESULT IN INCORRECT OUTPUT. CUSTOMER MUST EVALUATE THE ACCURACY AND
            SUITABILITY OF ANY OUTPUT FOR CUSTOMER&rsquo;S USE CASE, INCLUDING BY HUMAN REVIEW OF
            OUTPUT BEFORE OR PROMPTLY AFTER IT IS SHARED WITH PATIENTS. CUSTOMER UNDERSTANDS AND
            AGREES THAT OUTPUT MAY CONTAIN &ldquo;HALLUCINATIONS&rdquo; AND MAY BE INACCURATE,
            OBJECTIONABLE, INAPPROPRIATE, OR OTHERWISE UNSUITED TO CUSTOMER&rsquo;S PURPOSE, AND THAT
            OPERAAI SHALL NOT BE LIABLE FOR ANY DAMAGES CUSTOMER OR ANY THIRD PARTY ALLEGES TO INCUR
            AS A RESULT OF OR RELATING TO ANY OUTPUT OR OTHER CONTENT GENERATED BY OR ACCESSED ON OR
            THROUGH THE PLATFORM. ALL OUTPUT IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY
            KIND.
          </Caps>
          <P>
            9.5 <span className="font-medium text-[#1a1a17]">Anonymized data.</span> Notwithstanding
            anything to the contrary in this Agreement, OperaAI may collect, use, analyze, and
            otherwise process data or information derived from Customer Materials or Customer&rsquo;s
            use of the Platform, provided such data is aggregated and/or anonymized so that it does
            not identify Customer, any individual, or Customer&rsquo;s Confidential Information
            (&ldquo;Anonymized Data&rdquo;). All right, title, and interest in Anonymized Data belongs
            solely to OperaAI. OperaAI may use Anonymized Data for any lawful purpose, including
            analytics, benchmarking, training of artificial-intelligence and machine-learning models
            in de-identified form, product improvement, development, research, and marketing, and may
            make Anonymized Data publicly available in compliance with applicable law, provided it
            does not identify Customer, any individual, or Customer&rsquo;s Confidential Information.
          </P>
        </Section>

        <Section n="10" title="Confidential information">
          <P>
            Each Party agrees: (a) to receive and maintain in confidence all Confidential Information
            disclosed to it by or on behalf of the other Party; (b) not to use the other Party&rsquo;s
            Confidential Information except to perform its obligations or exercise its rights under
            this Agreement; (c) to limit internal dissemination of Confidential Information to
            employees and contractors who have a need to know and an obligation to protect it; and (d)
            to protect Confidential Information with at least the same degree of care it uses for its
            own similar information, and no less than reasonable care. A recipient may disclose
            Confidential Information on a need-to-know basis to employees, contractors, and
            representatives bound by enforceable confidentiality obligations. Confidential Information
            does not include information that: (i) is publicly known at the time of disclosure; (ii)
            is generally known in the industry before disclosure; (iii) becomes publicly known without
            fault of the recipient; (iv) is lawfully received from a third party without
            confidentiality obligations; or (v) is independently developed by the recipient. This
            Section does not prohibit disclosure required by law or court order, provided the
            recipient gives the disclosing Party prompt notice of any subpoena or similar request.
          </P>
        </Section>

        <Section n="11" title="Data security and health information">
          <P>
            11.1 <span className="font-medium text-[#1a1a17]">Compliance.</span> Each Party will at
            all times comply with its legal obligations with respect to the protection of personal
            data, including, as applicable, the Health Insurance Portability and Accountability Act of
            1996 and its implementing regulations (&ldquo;HIPAA&rdquo;) and applicable state privacy
            laws.
          </P>
          <P>
            11.2 <span className="font-medium text-[#1a1a17]">Business Associate Agreement.</span>{" "}
            To the extent OperaAI creates, receives, maintains, or transmits protected health
            information on behalf of Customer, the Parties&rsquo; performance is subject to the
            restrictions, requirements, and obligations of a Business Associate Agreement
            (&ldquo;BAA&rdquo;), which becomes part of this Agreement when mutually executed. Contact
            opera@getopera.ai if you have not received OperaAI&rsquo;s BAA.
          </P>
          <P>
            11.3 <span className="font-medium text-[#1a1a17]">Security program.</span> OperaAI will
            maintain an information security program (including internal policies and procedures)
            designed to (a) protect the Platform and Customer Materials against accidental or unlawful
            loss, access, or disclosure; (b) identify reasonably foreseeable internal and external
            risks to security and unauthorized access; and (c) minimize security risks, including
            through risk assessments and testing. Customer Materials are encrypted in transit and at
            rest and logically separated per customer. To the extent OperaAI maintains third-party
            certifications or audit reports regarding its security program, OperaAI will provide
            copies upon reasonable request.
          </P>
          <P>
            11.4 <span className="font-medium text-[#1a1a17]">Patient interactions.</span> Customer
            acknowledges that questions patients submit through the Ask Opera assistant, and related
            engagement activity on Patient Pages, are recorded and made available to Customer as part
            of the Services. Customer is responsible for providing patients any notices required by
            applicable law regarding such processing.
          </P>
        </Section>

        <Section n="12" title="Indemnification">
          <P>
            Customer agrees to indemnify, defend, and hold OperaAI and its affiliates and licensors
            harmless against any liabilities, damages, and costs (including reasonable
            attorneys&rsquo; fees) payable to a third party arising out of a third-party claim related
            to (a) Customer&rsquo;s or its patients&rsquo; use of the Platform; (b) any Customer
            Materials; or (c) Customer&rsquo;s provision of dental, orthodontic, or other healthcare
            services.
          </P>
        </Section>

        <Section n="13" title="Not medical, dental, or orthodontic advice">
          <Caps>
            OPERAAI DOES NOT DIRECTLY OFFER MEDICAL ADVICE OR DIAGNOSES, OR ENGAGE IN THE PRACTICE OF
            MEDICINE. THE PLATFORM — INCLUDING ALL VIDEOS, PATIENT PAGES, PRE-CONSULTATION WELCOME
            CONTENT, AND RESPONSES FROM THE ASK OPERA ASSISTANT — IS NOT INTENDED TO BE A SUBSTITUTE
            FOR PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT AND IS OFFERED FOR INFORMATIONAL
            AND COMMUNICATIVE PURPOSES ONLY. THE PLATFORM IS NOT INTENDED TO BE, AND MUST NOT BE TAKEN
            TO BE, THE PRACTICE OF MEDICINE, NURSING, PHARMACY, DENTAL, ORTHODONTIC, OR OTHER
            HEALTHCARE ADVICE BY OPERAAI. RESOURCES MADE AVAILABLE THROUGH THE PLATFORM ARE NOT A
            SUBSTITUTE FOR DIRECT, IN-PERSON HEALTHCARE SERVICES AND ARE NOT AN INDICATOR OF SPECIFIC
            RESULTS. CUSTOMER IS SOLELY RESPONSIBLE FOR THE REVIEW AND APPROVAL OF ALL OUTPUT AND
            MATERIALS PRESENTED TO ITS PATIENTS AND FOR THE PROVISION OF DENTAL, ORTHODONTIC, OR
            OTHER HEALTHCARE SERVICES TO ITS PATIENTS.
          </Caps>
        </Section>

        <Section n="14" title="Limitation of liability">
          <Caps>
            TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, IN NO EVENT SHALL OPERAAI BE LIABLE FOR
            (A) ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING,
            WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR
            ANY OTHER COMMERCIAL DAMAGES OR LOSSES; OR (B) AMOUNTS IN THE AGGREGATE IN EXCESS OF THE
            AMOUNTS PAID BY CUSTOMER TO OPERAAI FOR ACCESS TO AND USE OF THE PLATFORM IN THE TWELVE
            (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, WHETHER ARISING OUT OF OR
            RELATED TO CUSTOMER&rsquo;S USE OR INABILITY TO USE THE PLATFORM, HOWEVER CAUSED,
            REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, OR OTHERWISE) AND EVEN IF OPERAAI
            HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </Caps>
        </Section>

        <Section n="15" title="Term and termination">
          <P>
            15.1 <span className="font-medium text-[#1a1a17]">Term.</span> This Agreement is effective
            as of the earlier of the Effective Date of an executed Order Form or Customer&rsquo;s
            first acceptance or use of the Platform, and continues for the Subscription Term specified
            in the Order Form or, for online subscriptions, until the subscription is canceled
            (&ldquo;Subscription Term&rdquo;).
          </P>
          <P>
            15.2 <span className="font-medium text-[#1a1a17]">Termination for breach.</span> Either
            Party may terminate this Agreement for material breach by the other Party if (a) the
            non-breaching Party provides written notice of the breach; and (b) the breach is not cured
            within thirty (30) days after receipt of notice. OperaAI may additionally suspend or
            terminate Accounts for non-payment or for use that violates Section 4.4 or applicable law.
          </P>
          <P>
            15.3 <span className="font-medium text-[#1a1a17]">Effects of termination.</span> On
            termination for any reason, Customer&rsquo;s access to and use of the Platform ceases.
            For thirty (30) days following termination, Customer may arrange retrieval of Customer
            Materials by downloading them or contacting OperaAI. Following that period, OperaAI will
            delete Customer Materials to the extent required by applicable law, provided that OperaAI
            may continue to use Anonymized Data as set forth in this Agreement and may, at its
            discretion and subject to Customer&rsquo;s instruction, keep previously delivered Outputs
            available to the patients they were shared with.
          </P>
          <P>
            15.4 <span className="font-medium text-[#1a1a17]">Survival.</span> All sections of this
            Agreement which by their nature should survive termination will survive, including,
            without limitation, confidentiality obligations, warranty disclaimers, and limitations of
            liability. Each Party&rsquo;s termination rights are in addition to any suspension rights
            under this Agreement.
          </P>
        </Section>

        <Section n="16" title="General provisions">
          <P>
            16.1 <span className="font-medium text-[#1a1a17]">Entire agreement.</span> This Agreement
            is the complete and exclusive statement of the agreement between the Parties and
            supersedes any proposal or prior agreement, oral or written, and any other communications
            relating to its subject matter.
          </P>
          <P>
            16.2 <span className="font-medium text-[#1a1a17]">Force majeure.</span> Except for
            Customer&rsquo;s payment obligations, neither Party is liable for failure to perform its
            obligations if prevented by an event of Force Majeure — any event or condition beyond a
            Party&rsquo;s reasonable control that prevents, in whole or material part, performance, or
            renders it so difficult or costly as to be commercially unreasonable, including
            governmental action, riots, war, strikes, lockouts, shortages of energy or supplies,
            epidemics, pandemics, fire, flood, hurricane, typhoon, earthquake, lightning, or
            explosion.
          </P>
          <P>
            16.3 <span className="font-medium text-[#1a1a17]">Governing law.</span> This Agreement and
            all matters arising out of or in connection with it are governed exclusively by the laws
            of the State of Delaware, United States, without regard to its conflicts-of-law rules or
            any enactment of the Uniform Computer Information Transactions Act or the UN Convention on
            Contracts for the International Sale of Goods.
          </P>
          <P>
            16.4 <span className="font-medium text-[#1a1a17]">Dispute resolution.</span> The Parties
            shall first endeavor to settle any dispute arising out of or relating to this Agreement
            amicably. Failing that, the dispute shall be exclusively submitted to the jurisdiction of
            the competent courts of Santa Clara County, California, United States.
          </P>
          <P>
            16.5 <span className="font-medium text-[#1a1a17]">Assignment.</span> Neither Party shall
            assign or otherwise transfer this Agreement or any rights or obligations hereunder without
            the other Party&rsquo;s prior written consent, except that each Party may assign this
            Agreement to a successor to its business or assets to which this Agreement relates,
            whether by merger, sale of assets, sale of stock, reorganization, or otherwise. Any
            purported transfer without such consent is null and void. This Agreement binds and inures
            to the benefit of the Parties and their respective heirs, representatives, affiliates,
            successors, and permitted assigns.
          </P>
          <P>
            16.6 <span className="font-medium text-[#1a1a17]">Remedies.</span> In the event of a
            breach or threatened breach by either Party, the other Party shall have all applicable
            equitable and legal remedies.
          </P>
          <P>
            16.7 <span className="font-medium text-[#1a1a17]">Relationship of the parties.</span>{" "}
            Nothing in this Agreement creates an agency, partnership, or joint-venture relationship.
            Neither Party may assume or create obligations on behalf of the other or bind the other in
            any respect.
          </P>
          <P>
            16.8 <span className="font-medium text-[#1a1a17]">Waiver and modification.</span> Failure
            to enforce any right is not a waiver of subsequent enforcement. OperaAI may update these
            Terms from time to time; material changes will be notified (for example by email or
            in-product notice) at least fourteen (14) days before taking effect, and continued use of
            the Platform after that constitutes acceptance. For Customers on a mutually executed Order
            Form, no modification or waiver is effective unless in writing and signed by both
            Parties.
          </P>
          <P>
            16.9 <span className="font-medium text-[#1a1a17]">Severability.</span> If any provision of
            this Agreement is held invalid or unenforceable, the remainder continues in full force and
            effect to the fullest extent allowed by law.
          </P>
          <P>
            16.10 <span className="font-medium text-[#1a1a17]">Notices.</span> Notices to OperaAI
            shall be sent to OperaAI, Inc., 13342 Emeric Ct, Centreville, VA 20120 or
            opera@getopera.ai. Notices to Customer may be sent to the email address associated with
            Customer&rsquo;s Account or the address in the applicable Order Form.
          </P>
        </Section>

        <p className="cf-body mt-12 text-[13px] text-[#8a938c]">
          Questions about these Terms?{" "}
          <a href="mailto:opera@getopera.ai" className="underline underline-offset-2">
            opera@getopera.ai
          </a>
        </p>
      </div>
    </div>
  );
}
